/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Fifth.glb -T -d 
Files: Fifth.glb [11.37MB] > C:\Users\andre\Downloads\Fifth-transformed.glb [710.49KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Fifth-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-7.655, -1.804, 52.586]}
        rotation={[-1.459, -0.004, -2.608]}
        scale={0.615}
      >
        <mesh
          geometry={nodes.Main_hull_Death_Star_0.geometry}
          material={materials.Death_Star}
        />
        <mesh
          geometry={nodes.Main_hull_Death_Star_0_1.geometry}
          material={materials.Death_Star_Dish}
        />
        <mesh
          geometry={nodes.Main_hull_Death_Star_0_2.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Main_hull_Death_Star_0_3.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Fifth-transformed.glb");
