/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 First_New-v1.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";
import { ConditionalMesh } from "../utils/conditionalMesh";

export default function Model({ progress, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/First_New-v1.glb");
  const newmaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cessna_plane_Baked.geometry}
        material={newmaterials["fourth_texture_set_Baked.001"]}
        position={[52.876, 22.403, -30.043]}
        rotation={[0, 0.134, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Door.geometry}
        material={newmaterials["third_texutre_set_Baked.001"]}
        position={[4.978, 0.927, -16.477]}
        rotation={[0, 0.135, 0]}
      />
      <mesh
        geometry={nodes.Door_Two.geometry}
        material={newmaterials["third_texutre_set_Baked.001"]}
        position={[3.821, 0.875, -18.43]}
        rotation={[Math.PI, -0.135, 0]}
        scale={[-1.004, -1.012, -1.004]}
      />
      <ConditionalMesh progress={progress} showRange={[0.335, 0.64]}>
        <mesh
          geometry={nodes.First_Trees_Baked.geometry}
          material={newmaterials.fourth_texture_set_Baked}
          position={[29.8, -0.228, -13.801]}
          rotation={[-2.985, 0.885, 3.034]}
        />
      </ConditionalMesh>
      <mesh
        geometry={nodes.Fourth_Snowman_Baked.geometry}
        material={newmaterials["fourth_texture_set_Baked.001"]}
        position={[10.701, 0.089, -12.996]}
        rotation={[-2.985, 0.885, 3.034]}
      />
      <mesh
        geometry={nodes.House_Baked.geometry}
        material={newmaterials["third_texutre_set_Baked.001"]}
        position={[4.432, 3.777, -17.151]}
        rotation={[Math.PI / 2, 0, -0.135]}
      />
      <mesh
        geometry={nodes.Remove_This.geometry}
        material={newmaterials["third_texutre_set_Baked.001"]}
        position={[4.432, 3.777, -17.151]}
        rotation={[Math.PI / 2, 0, -0.135]}
      />
      <mesh
        geometry={nodes.Rotar_Baked.geometry}
        material={newmaterials["fourth_texture_set_Baked.001"]}
        position={[52.495, 22.305, -32.748]}
        rotation={[0, 0.134, -Math.PI / 2]}
      />
      <ConditionalMesh progress={progress} showRange={[0.335, 0.64]}>
        <mesh
          geometry={nodes.Snow_Background_Baked.geometry}
          material={newmaterials["second_texutre_set_Baked.001"]}
          position={[83.978, -1.359, 4.807]}
          rotation={[0, Math.PI / 2, 0]}
        />
      </ConditionalMesh>
    </group>
  );
}

// useGLTF.preload("/models/First_New-v1.glb");
