/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 First.glb -T -d 
Files: First.glb [26.33MB] > C:\Users\andre\Downloads\First-transformed.glb [1.64MB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/First-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-11.193, -0.205, 11.773]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh geometry={nodes.Object_2.geometry} material={materials.Sand} />
        <mesh
          geometry={nodes.Object_2_1.geometry}
          material={materials.Sandstone}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/First-transformed.glb");
