/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Fourth.glb -T -d 
Files: Fourth.glb [6MB] > C:\Users\andre\Downloads\Fourth-transformed.glb [387.46KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Fourth-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-20.149, -0.597, 6.854]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials.Dandelion}
        />
        <mesh
          geometry={nodes.Object_54_1.geometry}
          material={materials.Glowstone}
        />
        <mesh
          geometry={nodes.Object_54_2.geometry}
          material={materials.Stone}
        />
        <mesh
          geometry={nodes.Object_54_3.geometry}
          material={materials["material.001"]}
        />
        <mesh
          geometry={nodes.Object_54_4.geometry}
          material={materials.Leaves}
        />
        <mesh
          geometry={nodes.Object_54_5.geometry}
          material={materials.Redstone_Torch_active}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Fourth-transformed.glb");
