/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Fourth.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { convertMaterialsToBasic } from "../utils/convertToBasic";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Fourth.glb");
  const newmaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Fourth_Floor_Baked.geometry}
        material={newmaterials.second_floor_Baked}
        position={[-6.613, -1.091, -32.441]}
      />
      <mesh
        geometry={nodes.Fourth_Wall_Baked.geometry}
        material={newmaterials.first_wall_Baked}
        position={[-19.505, -2.498, -75.294]}
        rotation={[Math.PI / 2, 0, 3.003]}
      />
      <mesh
        geometry={nodes.Track002_Baked.geometry}
        material={newmaterials.combined_Baked}
        position={[-6.432, -1.407, 3.62]}
      />
      <mesh
        geometry={nodes.House_Baked001_Baked.geometry}
        material={newmaterials.combined_Baked}
        position={[-43.528, 8.245, -68.841]}
        rotation={[Math.PI / 2, 0, -0.772]}
      />
    </group>
  );
}

// useGLTF.preload("/models/Fourth.glb");
