/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Second-v2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { ConditionalMesh } from "../utils/conditionalMesh";

export default function Model({ progress, ...props }) {
  const { nodes, materials } = useGLTF("/models/Second-v2.glb");
  return (
    <group {...props} dispose={null}>
      <ConditionalMesh progress={progress} showRange={[0.64, 0.819]}>
        <group
          position={[3.235, 0.789, -22.545]}
          rotation={[0, 0.181, 0]}
          scale={0.14}
        >
          <mesh
            geometry={nodes.Cube004.geometry}
            material={materials["Bamboo Inner"]}
          />
          <mesh
            geometry={nodes.Cube004_1.geometry}
            material={materials.Bamboo}
          />
          <mesh
            geometry={nodes.Cube004_2.geometry}
            material={materials.Background}
          />
          <mesh
            geometry={nodes.Cube004_3.geometry}
            material={materials["Pusheen Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_4.geometry}
            material={materials["Codrops Sushi Store"]}
          />
          <mesh
            geometry={nodes.Cube004_5.geometry}
            material={materials["Codrops Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_6.geometry}
            material={materials["Egg White"]}
          />
          <mesh
            geometry={nodes.Cube004_7.geometry}
            material={materials["Egg yolk"]}
          />
          <mesh
            geometry={nodes.Cube004_8.geometry}
            material={materials["Miffy Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_9.geometry}
            material={materials["Ramen Bowl"]}
          />
          <mesh
            geometry={nodes.Cube004_10.geometry}
            material={materials["Chopstick Black"]}
          />
          <mesh
            geometry={nodes.Cube004_11.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Cube004_12.geometry}
            material={materials["Chair Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_13.geometry}
            material={materials.Noodles}
          />
          <mesh
            geometry={nodes.Cube004_14.geometry}
            material={materials["Wood board"]}
          />
          <mesh geometry={nodes.Cube004_15.geometry} material={materials.Pot} />
          <mesh
            geometry={nodes.Cube004_16.geometry}
            material={materials["Bamboo Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_17.geometry}
            material={materials["Bamboo Shoot.001"]}
          />
          <mesh
            geometry={nodes.Cube004_18.geometry}
            material={materials["Pusheen Body"]}
          />
          <mesh
            geometry={nodes.Cube004_19.geometry}
            material={materials["Pusheen Eyes"]}
          />
          <mesh
            geometry={nodes.Cube004_20.geometry}
            material={materials.Grayish}
          />
          <mesh
            geometry={nodes.Cube004_21.geometry}
            material={materials.Star}
          />
          <mesh
            geometry={nodes.Cube004_22.geometry}
            material={materials.Vent}
          />
          <mesh
            geometry={nodes.Cube004_23.geometry}
            material={materials["Soy Sauce label"]}
          />
          <mesh
            geometry={nodes.Cube004_24.geometry}
            material={materials["Soy sauce"]}
          />
          <mesh
            geometry={nodes.Cube004_25.geometry}
            material={materials.Paper}
          />
          <mesh
            geometry={nodes.Cube004_26.geometry}
            material={materials["Gray Pot"]}
          />
          <mesh
            geometry={nodes.Cube004_27.geometry}
            material={materials.Bowl}
          />
          <mesh
            geometry={nodes.Cube004_28.geometry}
            material={materials["Miffy Head"]}
          />
          <mesh
            geometry={nodes.Cube004_29.geometry}
            material={materials["Miffy Eyes"]}
          />
          <mesh
            geometry={nodes.Cube004_30.geometry}
            material={materials["Miffy Shirt"]}
          />
          <mesh
            geometry={nodes.Cube004_31.geometry}
            material={materials["Boris Black"]}
          />
          <mesh geometry={nodes.Cube004_32.geometry} material={materials.Hat} />
          <mesh
            geometry={nodes.Cube004_33.geometry}
            material={materials.Blue}
          />
          <mesh
            geometry={nodes.Cube004_34.geometry}
            material={materials["Bao Steamer"]}
          />
          <mesh
            geometry={nodes.Cube004_35.geometry}
            material={materials["Bao Steamer Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_36.geometry}
            material={materials["Shusi Plate"]}
          />
          <mesh
            geometry={nodes.Cube004_37.geometry}
            material={materials.Chopstick}
          />
          <mesh
            geometry={nodes.Cube004_38.geometry}
            material={materials["Chopstick.001"]}
          />
          <mesh
            geometry={nodes.Cube004_39.geometry}
            material={materials.Rice}
          />
          <mesh
            geometry={nodes.Cube004_40.geometry}
            material={materials.Salmon}
          />
          <mesh geometry={nodes.Cube004_41.geometry} material={materials.Egg} />
          <mesh
            geometry={nodes.Cube004_42.geometry}
            material={materials["Boris Black"]}
          />
          <mesh
            geometry={nodes.Cube004_43.geometry}
            material={materials.Onion}
          />
          <mesh
            geometry={nodes.Cube004_44.geometry}
            material={materials["Miffy Outline.001"]}
          />
          <mesh
            geometry={nodes.Cube004_45.geometry}
            material={materials.Shrimp}
          />
          <mesh
            geometry={nodes.Cube004_46.geometry}
            material={materials.Wasabi}
          />
          <mesh
            geometry={nodes.Cube004_47.geometry}
            material={materials["Wasabi Outline"]}
          />
          <mesh
            geometry={nodes.Cube004_48.geometry}
            material={materials["Red Cabbage"]}
          />
          <mesh
            geometry={nodes.Cube004_49.geometry}
            material={materials["Soy Sauce Holder"]}
          />
          <mesh
            geometry={nodes.Cube004_50.geometry}
            material={materials.Avocado}
          />
          <mesh
            geometry={nodes.Cube004_51.geometry}
            material={materials["Avocado Border"]}
          />
          <mesh
            geometry={nodes.Cube004_52.geometry}
            material={materials.Crab}
          />
          <mesh
            geometry={nodes.Cube004_53.geometry}
            material={materials["Seasmee Seed"]}
          />
          <mesh
            geometry={nodes.Cube004_54.geometry}
            material={materials["Bao Steamer Outline.001"]}
          />
          <mesh
            geometry={nodes.Cube004_55.geometry}
            material={materials["Bamboo Brown"]}
          />
          <mesh
            geometry={nodes.Cube004_56.geometry}
            material={materials["Bamboo Inner Brown"]}
          />
          <mesh
            geometry={nodes.Cube004_57.geometry}
            material={materials.Dirt}
          />
        </group>
      </ConditionalMesh>
    </group>
  );
}

useGLTF.preload("/models/Second-v2.glb");
