/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Second.glb -T -d 
Files: Second.glb [446.88KB] > C:\Users\andre\Downloads\Second-transformed.glb [119.96KB] (73%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Second-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.049, 1.166, 12.249]}
        rotation={[0, -1.419, 0]}
        scale={0.059}
      >
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0.geometry
          }
          material={materials["material_0.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_1.geometry
          }
          material={materials["zeimport_poly_XSIPOLYCLS.underground1.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_2.geometry
          }
          material={materials["zeimport_poly1_XSIPOLYCLS.qblock.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_3.geometry
          }
          material={materials["zeimport_poly4_XSIPOLYCLS.qblocktop.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_4.geometry
          }
          material={materials["zeimport_poly6_XSIPOLYCLS.flagblock.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_5.geometry
          }
          material={materials["zeimport_poly17_XSIPOLYCLS.castle.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_6.geometry
          }
          material={materials["zeimport_poly18_XSIPOLYCLS.flag.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_7.geometry
          }
          material={materials["zeimport_poly19_XSIPOLYCLS.underbrick.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_8.geometry
          }
          material={materials["zeimport_poly20_XSIPOLYCLS.coins.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_9.geometry
          }
          material={materials["zeimport_poly2_XSIPOLYCLS.pipetop1.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_10.geometry
          }
          material={materials["zeimport_poly3_XSIPOLYCLS.pipe1.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_11.geometry
          }
          material={materials["zeimport_poly8_XSIPOLYCLS.brick1.001"]}
        />
        <mesh
          geometry={
            nodes.nes_bldg_smb11_zeimport_poly5_XSIPOLYCLSground1_0_12.geometry
          }
          material={materials["zeimport_poly12_XSIPOLYCLS.castleside1.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Second-transformed.glb");
