/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Third_New-v3.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

import { convertMaterialsToBasic } from "../utils/convertToBasic";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { ConditionalMesh } from "../utils/conditionalMesh";

export default function Model({ progress, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Third_New-v3.glb");
  const newmaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <ConditionalMesh progress={progress} showRange={[0.755, 0.99]}>
        <mesh
          geometry={nodes.First_Paper_Baked.geometry}
          material={newmaterials.first_Baked}
          position={[0.168, -0.712, -44.536]}
          rotation={[-Math.PI / 2, 0, -3.003]}
          scale={[-20.58, -2.026, -24.108]}
        />
        <mesh
          geometry={nodes.Third_Baked.geometry}
          material={newmaterials.third_Baked}
          position={[6.585, -4.978, -41.493]}
          rotation={[Math.PI, -0.138, Math.PI]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Hidden_Door.geometry}
          material={newmaterials.first_Baked}
          position={[0.911, 1.124, -44.639]}
          rotation={[-Math.PI / 2, 0, -3.003]}
          scale={[-20.58, -2.026, -24.108]}
        />
        <mesh
          geometry={nodes.Ocean002.geometry}
          material={newmaterials.third_Baked}
          position={[3.697, -5.756, -41.602]}
          rotation={[Math.PI, -0.138, Math.PI]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Ocean003.geometry}
          material={newmaterials.third_Baked}
          position={[6.585, -4.978, -41.493]}
          rotation={[Math.PI, -0.138, Math.PI]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Ocean.geometry}
          material={newmaterials.third_Baked}
          position={[-3.971, -6.047, -40.799]}
          rotation={[Math.PI, -0.138, Math.PI]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Ocean001.geometry}
          material={newmaterials.third_Baked}
          position={[-1.568, -6.83, -40.595]}
          rotation={[Math.PI, -0.138, Math.PI]}
          scale={0.19}
        />
        <group
          position={[5.891, -2.478, -43.788]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        >
          <mesh
            geometry={nodes.Plane017.geometry}
            material={newmaterials.second_Baked}
          />
          <mesh
            geometry={nodes.Plane017_1.geometry}
            material={newmaterials.third_Baked}
          />
        </group>
        <mesh
          geometry={nodes.Right_Arm.geometry}
          material={newmaterials.second_Baked}
          position={[6.6, 1.406, -43.773]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Left_Arm.geometry}
          material={newmaterials.second_Baked}
          position={[4.968, 1.501, -43.489]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        />
        <group
          position={[-1.144, -2.096, -42.695]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        >
          <mesh
            geometry={nodes.Plane020.geometry}
            material={newmaterials.second_Baked}
          />
          <mesh
            geometry={nodes.Plane020_1.geometry}
            material={newmaterials.third_Baked}
          />
        </group>
        <mesh
          geometry={nodes.Sun.geometry}
          material={newmaterials.second_Baked}
          position={[-4.926, 5.116, -42.575]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Seagull.geometry}
          material={newmaterials.second_Baked}
          position={[0.575, 1.074, -42.836]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Seagull001.geometry}
          material={newmaterials.second_Baked}
          position={[0.575, 1.074, -42.836]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        />
        <mesh
          geometry={nodes.Seagull002.geometry}
          material={newmaterials.second_Baked}
          position={[0.575, 1.074, -42.836]}
          rotation={[-1.566, -0.042, -3.004]}
          scale={0.19}
        />
      </ConditionalMesh>
    </group>
  );
}

// useGLTF.preload("/Third_New-v3.glb");
