/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Third-v2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Third-v2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Third_Hogwarts_Baked.geometry}
        material={materials["Third_Hogwarts_Baked.002"]}
        position={[-0.903, 0.387, 6.892]}
        rotation={[-Math.PI, -0.149, 0]}
      />
      <mesh
        geometry={nodes.Third_Reveal.geometry}
        material={materials["Third_Hogwarts_Baked.002"]}
        position={[-0.903, 0.387, 6.892]}
        rotation={[-Math.PI, -0.149, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/Third-v2.glb");
